---
deployment:
  tasks:
    - DEPLOYPATH=$(pwd)
    - /bin/cp .env.example $DEPLOYPATH/.env
    - export COMPOSER_HOME=$HOME/.composer
    - /opt/cpanel/composer/bin/composer install --no-interaction --prefer-dist --optimize-autoloader --working-dir=$DEPLOYPATH